//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBackup
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileBackupSQLEntities : DbContext
    {
        public FileBackupSQLEntities()
            : base("name=FileBackupSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileBackupHistory> FileBackupHistories { get; set; }
        public virtual DbSet<FileBackupMain> FileBackupMains { get; set; }
        public virtual DbSet<FilesUpdatedOrAdded> FilesUpdatedOrAddeds { get; set; }
    }
}
