//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBackup
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FileBackupMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileBackupMain()
        {
            this.FileBackupHistories = new ObservableCollection<FileBackupHistory>();
        }
    
        public int PK_FileId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> FileLastEditedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<FileBackupHistory> FileBackupHistories { get; set; }
    }
}
