//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBackup
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FilesUpdatedOrAdded
    {
        public string FileFullNamePath { get; set; }
        public Nullable<int> FileChangeType { get; set; }
        public Nullable<System.DateTime> FileChangeDateTime { get; set; }
    }
}
